ProyectoWeb/ProyectoWeb/urls.py
from django.contrib import admin
from django.urls import path ,include

#estas urs son de todo el proyecto en general, asi que vamos a haver un archivo urls.py para cada aplicacion y asi que cada una tenga sus urls
urlpatterns = [
    path('admin/', admin.site.urls),  
    #asi se enlazan las urls del pryecto con las de la app
    path('',include('ProyectoWebApp.urls')), 
    #ya a la url se le debe agregar ProyectoWebApp/ 
    path('servicios/',include('servicios.urls')), #se agrega la url de la app servicios 
    path('blog/',include('blog.urls')),
    path('contacto/',include('contacto.urls')), 
    path('tiendas/',include('tiendas.urls')), 
    path('carro/',include('carro.urls')), 
    path('autenticacion/',include ('autenticacion.urls')),
    
]

ProyectoWeb/blog/urls.py
from django.urls import path  
from . import views 
from django.conf import settings 
from django.conf.urls.static import static
urlpatterns = [ 
    path('',views.blog_vista, name="blog"),
    path('categoria/<categoria_id>',views.categoria, name='categoria')
]

ProyectoWeb/carro/urls.py
from django.urls import path  
from . import views 

app_name="carro"
urlpatterns = [  
    path("agregar/<int:producto_id>/",views.agregar_producto, name="agregar"), # se llama a la vista de agregar productos
    path("eliminar/<int:producto_id>/",views.eliminar_producto, name="eliminar"), # se llama a la vista de eliminar productos
    path("restar/<int:producto_id>/",views.restar_producto, name="restar"), # se llama a la vista de restarproductos
    path("limpiar/<int:producto_id>/",views.limpiar_carro, name="limpiar"), # se llama a la vista de limpiar carro 
    
]

ProyectoWeb/tiendas/urls.py
from django.urls import path  
from . import views  
from carro import views as vp
urlpatterns = [ 
    path('',views.tienda_vista,name="tiendas"), 
    
]

ProyectoWeb/tiendas/models.py
from django.db import models

# Create your models here. 

#modelo para las cateforias de los productos
class CategoriaProductos(models.Model): 
    nombre=models.CharField(max_length=50) 
    created=models.DateTimeField(auto_now_add=True) #pone la fecha de creado automaticamente
    updated=models.DateTimeField(auto_now_add=True)
    class Meta: 
        verbose_name='categoria producto' #especificar el nombre que aparecerá en la base de datos
        verbose_name_plural='categorias productos' 
    def __str__(self): 
        return self.nombre



class producto(models.Model): #vamos a crear los modelos para productos y categorias
    nombre_producto=models.CharField(max_length=50) 
    precio=models.FloatField() 
    imagen=models.ImageField(upload_to='tienda',null=True,blank=True) #el imagefield se usa para poder procesar imagenes, para usar imagenes se debe de tener pillow, el upload es para que se suba a la carptea servicios dentro de media 
    disponibilidad=models.BooleanField(default=True)
    categorias=models.ForeignKey(CategoriaProductos,on_delete=models.CASCADE)#relacionamos las dos tablas
    created=models.DateTimeField(auto_now_add=True) #pone la fecha de creado automaticamente
    updated=models.DateTimeField(auto_now_add=True)  

    class Meta: 
            verbose_name='producto' #especificar el nombre que aparecerá en la base de datos
            verbose_name_plural='productos' 
    def __str__(self): 
        return self.nombre_producto

ProyectoWeb/carro/views.py
from django.shortcuts import render
from .carro import Carro 
from tiendas.models import producto as p 
from django.shortcuts import redirect
# Create your views here.
def agregar_producto(request,producto_id): #vamos a hacer la vista agregar productos
    carro=Carro(request) #se llama a la clase carro y se crea un objeto 
    producto=p.objects.get(id=producto_id) #almacenar los id de los productos 
    carro.agregar(producto=producto) #se llama a la funcion agreagr de la clase carro con el producto que definimos antes 
    return redirect("tiendas") #que redireccione a la tienda  

def eliminar_producto(request,producto_id): #vamos a hacer la vista eliminar productos
    carro=Carro(request) #se llama a la clase carro y se crea un objeto 
    producto=p.objects.get(id=producto_id) #almacenar los id de los productos 
    carro.eliminar(producto=producto) #se llama a la funcion eliminar de la clase carro con el producto que definimos antes 
    return redirect("tiendas") #que redireccione a la tienda  

def restar_producto(request,producto_id): #vamos a hacer la vista restar productos
    carro=Carro(request) #se llama a la clase carro y se crea un objeto 
    producto=p.objects.get(id=producto_id) #almacenar los id de los productos 
    carro.restar_producto(producto=producto) #se llama a la funcion restar productos de la clase carro con el producto que definimos antes 
    return redirect("tiendas") #que redireccione a la tienda  

def limpiar_carro(request,producto_id): #y aqui la funcion para vaciar el carro 
    carro=Carro(request) 
    carro.limipar_carro() 
    return redirect("tiendas")

ProyectoWeb/tiendas/views.py
from django.shortcuts import render
from .models import producto,CategoriaProductos
# Create your views here. 

#vamos a hacer el mismo proceso que con blog, vamos a mortrar los productos con sus categorias
def tienda_vista(request):   
    productos=producto.objects.all()
    return render(request,"tienda/Tienda.html",{'productos':productos}) 


def categoriaProductos(request,categoria_id): 
    categoria=CategoriaProductos.objects.get(id=categoria_id) #se pone para que traiga todos los ids de las categorias
    productos=producto.objects.filter(categorias=categoria_id) #y asi trae todos los posts con ese id
    return render(request,"tienda/categorias.html",{'categorias':categoria,'productos':productos})

ProyectoWeb/tiendas/templates/tienda/carro/widget_carro.html
<table class="table table-bordered" style="color: white;">

    <thead>
        <tr>

            <th colspan="3" class="text-center">

                Carro compras

            </th>

        </tr>

        <tr>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Suma</th>


        </tr>


    </thead>

    <tbody>
        {% if request.session.carro.items %}
            {% for key, value in request.session.carro.items %}
                <tr class="text-center">

                    <td>{{value.nombre_producto}}</td>
                    <td>{{value.cantidad}}</td>
                    <td>

                        <a href="{% url 'carro:agregar' value.producto_id %}" class="btn btn-sm btn-success">+</a>
                        <a href="{% url 'carro:restar' value.producto_id %}" class="btn btn-sm btn-success">-</a>
                        <a href="{% url 'carro:eliminar' value.producto_id %}" class="btn btn-sm btn-success">x</a><br/>  
                            
                        {{value.precio}} K

                    </td>

                </tr>

            {% endfor %}

        {% else %}
            <tr>

                <td colspan="3">
                    <div class="alert alert-danger text-center">

                        Sin productos
                    </div>

                </td>

            </tr>
        {% endif %}
    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">

                Total: {{importe_total_carro}} K


            </td>


        </tr>
    </tfoot>


</table>